version: '3'

services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    # Uncomment the following lines to use GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Interactive mode
    stdin_open: true
    tty: true