version: '3.8'

services:
  geopixel-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geopixel-api-optimized
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./vis_output:/app/vis_output
    environment:
      # Keep only essential optimizations
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Remove resource limits that may be constraining performance
    restart: unless-stopped
    # Interactive mode for easier debugging if needed
    stdin_open: true
    tty: true